baseURL = 'https://trideeindhoven.github.io/website/'
title = "CloudAware Technical Consultancy"
author = "Jeroen Hermans"
languageCode = "nl"
DefaultContentLanguage = "nl"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['yealink', 'blog']

  googleFonts = false

  [params.logo]
    main = "img/logo/cloudaware.png"
    alt = "CloudAware Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    #size = "h-14"
    size = "h-20"

  [params.site]
    name = "CloudAware Technical Consultancy"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "CloudAware Technical Consultancy"
    meta_og_title = "CloudAware Technical Consultancy"
    meta_og_type = "website"
    meta_og_url = "https://cloudaware.eu"
    #meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    #meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    #meta_twitter_card = "summary_large_image"
    #meta_twitter_site = "@username"
    #meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    identifier = "support"
    name = "Support"
    url = "/support"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "Over"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "spreker"
    name = "Spreker"
    url = "/spreker/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  [[menu.main]]
    identifier = "cve"
    name = "CVE"
    url = "/cve/"
    weight = 6

  # Footer Menu
  [[menu.footer]]
    name = "Privacy statement"
    url = "/privacybeleid"
      weight = 1

  [[menu.footer]]
    name = "Cookieverklaring"
    url = "/cookieverklaring"
      weight = 2

  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 3

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/gitaware"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 4
